"use client";

import React, { useState } from 'react';
import "../app/components/footer.css";
import { Divider } from '@mui/material'

export default function Footer() {
    const [isPopupVisible, setIsPopupVisible] = useState(false);

    const togglePopup = () => {
        setIsPopupVisible(!isPopupVisible);
    }

    return (
        <footer>
            <div className="footer-container">
                <button 
                    id="back-to-top" 
                    onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
                >
                    BACK TO TOP
                </button>
                <button className="popup" onClick={togglePopup}>
                    FAQ
                    <span className={`popuptext ${isPopupVisible ? "show" : ""}`} id="myPopup">
                        <ul>
                            <li><strong>Is this a paid website?</strong></li>
                            <li>It is free to use, but some of the features will be paid. Payment is required to access all features</li>
                            <br></br>
                            <Divider
                                sx={{
                                    my: 1,
                                    height: 1,
                                    background: 'linear-gradient(to right, #2abfee, #2ee37e)',
                                    borderRadius: 1,
                                }}
                                />
                            <li><strong>Are the cards generated by AI?</strong></li>
                            <li>Yes, you can search any topic</li>
                            <br></br>
                            <Divider
                                sx={{
                                    my: 1,
                                    height: 1,
                                    background: 'linear-gradient(to right, #2abfee, #2ee37e)',
                                    borderRadius: 1,
                                }}
                                />
                            <li><strong>Can I customize my own cards?</strong></li>
                            <li>Yes, you can add or edit the flashcards</li>
                            <br></br>
                            <Divider
                                sx={{
                                    my: 1,
                                    height: 1,
                                    background: 'linear-gradient(to right, #2abfee, #2ee37e)',
                                    borderRadius: 1,
                                }}
                                />
                            <li><strong>Is my search protected?</strong></li>
                            <li>Yes, all data is private</li>
                        </ul>
                    </span>
                </button>
                <div className="footer-bottom">
                    <p>&copy; 2024 AIZOOCARDS</p>
                </div>
            </div>
        </footer>
    )
}